version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
  truffle:
    build:
      context: .
      dockerfile: ./truffle-dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./smartContract:/project
    depends_on:
      - ganache